name: pi_mobile_app
description: Application mobile PI
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - env.json
    - assets/
